title: <p align=”center”> Krishnamoorthy V </p>
logo: /assets/img/logo.png
description: Possess 7.2 years of experience in IT (6 years in Mainframe Application and 1.2 years in Python & Splunk).
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
